package com.java.rollercoaster.pojo;

import java.util.Date;

public class Announcement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcementId
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Integer announcementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.date
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.text
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcementId
     *
     * @return the value of announcement.announcementId
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Integer getAnnouncementid() {
        return announcementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcementId
     *
     * @param announcementid the value for announcement.announcementId
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setAnnouncementid(Integer announcementid) {
        this.announcementid = announcementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.date
     *
     * @return the value of announcement.date
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.date
     *
     * @param date the value for announcement.date
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.text
     *
     * @return the value of announcement.text
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.text
     *
     * @param text the value for announcement.text
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}