package com.java.rollercoaster.pojo;

import java.util.Date;

public class Announcement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcement_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    private Integer announcementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.date
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.text
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcement_id
     *
     * @return the value of announcement.announcement_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public Integer getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcement_id
     *
     * @param announcementId the value for announcement.announcement_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.date
     *
     * @return the value of announcement.date
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.date
     *
     * @param date the value for announcement.date
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.text
     *
     * @return the value of announcement.text
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.text
     *
     * @param text the value for announcement.text
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}