package com.java.rollercoaster.pojo;

public class Appointment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointmentID
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    private String appointmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.event_name
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.phone_number
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointmentID
     *
     * @return the value of appointment.appointmentID
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    public String getAppointmentid() {
        return appointmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointmentID
     *
     * @param appointmentid the value for appointment.appointmentID
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    public void setAppointmentid(String appointmentid) {
        this.appointmentid = appointmentid == null ? null : appointmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.event_name
     *
     * @return the value of appointment.event_name
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.event_name
     *
     * @param eventName the value for appointment.event_name
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.phone_number
     *
     * @return the value of appointment.phone_number
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.phone_number
     *
     * @param phoneNumber the value for appointment.phone_number
     *
     * @mbggenerated Sat Nov 07 10:34:12 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }
}