package com.java.rollercoaster.pojo;

public class Appointment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointmentID
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    private String appointmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.event_name
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.user_id
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointmentID
     *
     * @return the value of appointment.appointmentID
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    public String getAppointmentid() {
        return appointmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointmentID
     *
     * @param appointmentid the value for appointment.appointmentID
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    public void setAppointmentid(String appointmentid) {
        this.appointmentid = appointmentid == null ? null : appointmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.event_name
     *
     * @return the value of appointment.event_name
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.event_name
     *
     * @param eventName the value for appointment.event_name
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.user_id
     *
     * @return the value of appointment.user_id
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.user_id
     *
     * @param userId the value for appointment.user_id
     *
     * @mbggenerated Sun Nov 08 20:55:14 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}