package com.java.rollercoaster.pojo;

import java.util.Date;

public class Appointment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String appointmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.event_name
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.user_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.valid_date
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Date validDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_id
     *
     * @return the value of appointment.appointment_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getAppointmentId() {
        return appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_id
     *
     * @param appointmentId the value for appointment.appointment_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId == null ? null : appointmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.event_name
     *
     * @return the value of appointment.event_name
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.event_name
     *
     * @param eventName the value for appointment.event_name
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.user_id
     *
     * @return the value of appointment.user_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.user_id
     *
     * @param userId the value for appointment.user_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.valid_date
     *
     * @return the value of appointment.valid_date
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.valid_date
     *
     * @param validDate the value for appointment.valid_date
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }
}