package com.java.rollercoaster.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.java.rollercoaster.service.model.enumeration.FacilityStatus;
import java.util.Date;

public class Facility {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.facility_name
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    private String facilityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.facility_status
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    private FacilityStatus FacilityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.facility_introduction
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    private String facilityIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.facility_open_time
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    @JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8:00")
    private Date facilityOpenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.facility_close_time
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    @JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8:00")
    private Date facilityCloseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.queue_status
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    private Integer queueStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.facility_image
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    private String facilityImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.rating
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    private Float rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facility.rating_people
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    private Integer ratingPeople;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.facility_name
     *
     * @return the value of facility.facility_name
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public String getFacilityName() {
        return facilityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.facility_name
     *
     * @param facilityName the value for facility.facility_name
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName == null ? null : facilityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.facility_status
     *
     * @return the value of facility.facility_status
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public FacilityStatus getFacilityStatus() {
        return FacilityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.facility_status
     *
     * @param FacilityStatus the value for facility.facility_status
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setFacilityStatus(FacilityStatus FacilityStatus) {
        this.FacilityStatus = FacilityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.facility_introduction
     *
     * @return the value of facility.facility_introduction
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public String getFacilityIntroduction() {
        return facilityIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.facility_introduction
     *
     * @param facilityIntroduction the value for facility.facility_introduction
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setFacilityIntroduction(String facilityIntroduction) {
        this.facilityIntroduction = facilityIntroduction == null ? null : facilityIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.facility_open_time
     *
     * @return the value of facility.facility_open_time
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public Date getFacilityOpenTime() {
        return facilityOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.facility_open_time
     *
     * @param facilityOpenTime the value for facility.facility_open_time
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setFacilityOpenTime(Date facilityOpenTime) {
        this.facilityOpenTime = facilityOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.facility_close_time
     *
     * @return the value of facility.facility_close_time
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public Date getFacilityCloseTime() {
        return facilityCloseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.facility_close_time
     *
     * @param facilityCloseTime the value for facility.facility_close_time
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setFacilityCloseTime(Date facilityCloseTime) {
        this.facilityCloseTime = facilityCloseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.queue_status
     *
     * @return the value of facility.queue_status
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public Integer getQueueStatus() {
        return queueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.queue_status
     *
     * @param queueStatus the value for facility.queue_status
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setQueueStatus(Integer queueStatus) {
        this.queueStatus = queueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.facility_image
     *
     * @return the value of facility.facility_image
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public String getFacilityImage() {
        return facilityImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.facility_image
     *
     * @param facilityImage the value for facility.facility_image
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setFacilityImage(String facilityImage) {
        this.facilityImage = facilityImage == null ? null : facilityImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.rating
     *
     * @return the value of facility.rating
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public Float getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.rating
     *
     * @param rating the value for facility.rating
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setRating(Float rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facility.rating_people
     *
     * @return the value of facility.rating_people
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public Integer getRatingPeople() {
        return ratingPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facility.rating_people
     *
     * @param ratingPeople the value for facility.rating_people
     *
     * @mbggenerated Thu Nov 26 14:31:02 CST 2020
     */
    public void setRatingPeople(Integer ratingPeople) {
        this.ratingPeople = ratingPeople;
    }
}