package com.java.rollercoaster.pojo;

import java.util.Date;

public class QuickPass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quickpass.quickpass_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    private String quickpassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quickpass.start_time
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quickpass.facility_name
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    private String facilityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quickpass.user_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quickpass.quickpass_id
     *
     * @return the value of quickpass.quickpass_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public String getQuickpassId() {
        return quickpassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quickpass.quickpass_id
     *
     * @param quickpassId the value for quickpass.quickpass_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public void setQuickpassId(String quickpassId) {
        this.quickpassId = quickpassId == null ? null : quickpassId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quickpass.start_time
     *
     * @return the value of quickpass.start_time
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quickpass.start_time
     *
     * @param startTime the value for quickpass.start_time
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quickpass.facility_name
     *
     * @return the value of quickpass.facility_name
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public String getFacilityName() {
        return facilityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quickpass.facility_name
     *
     * @param facilityName the value for quickpass.facility_name
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName == null ? null : facilityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quickpass.user_id
     *
     * @return the value of quickpass.user_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quickpass.user_id
     *
     * @param userId the value for quickpass.user_id
     *
     * @mbggenerated Sat Dec 05 01:04:53 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}