package com.java.rollercoaster.pojo;

import java.util.Date;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_ID
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    private String ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.phone_number
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.status
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.price
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.valid_date
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    private Date validDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_ID
     *
     * @return the value of ticket.ticket_ID
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public String getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_ID
     *
     * @param ticketId the value for ticket.ticket_ID
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId == null ? null : ticketId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.phone_number
     *
     * @return the value of ticket.phone_number
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.phone_number
     *
     * @param phoneNumber the value for ticket.phone_number
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.status
     *
     * @return the value of ticket.status
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.status
     *
     * @param status the value for ticket.status
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.price
     *
     * @return the value of ticket.price
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.price
     *
     * @param price the value for ticket.price
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.valid_date
     *
     * @return the value of ticket.valid_date
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.valid_date
     *
     * @param validDate the value for ticket.valid_date
     *
     * @mbggenerated Sat Nov 07 09:43:37 CST 2020
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }
}