package com.java.rollercoaster.pojo;

import com.java.rollercoaster.service.model.enumeration.TicketType;

public class TicketPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticketPrice.ticket_type
     *
     * @mbggenerated Sun Nov 22 15:26:01 CST 2020
     */
    private TicketType TicketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticketPrice.ticket_price
     *
     * @mbggenerated Sun Nov 22 15:26:01 CST 2020
     */
    private Float ticketPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticketPrice.ticket_type
     *
     * @return the value of ticketPrice.ticket_type
     *
     * @mbggenerated Sun Nov 22 15:26:01 CST 2020
     */
    public TicketType getTicketType() {
        return TicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticketPrice.ticket_type
     *
     * @param TicketType the value for ticketPrice.ticket_type
     *
     * @mbggenerated Sun Nov 22 15:26:01 CST 2020
     */
    public void setTicketType(TicketType TicketType) {
        this.TicketType = TicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticketPrice.ticket_price
     *
     * @return the value of ticketPrice.ticket_price
     *
     * @mbggenerated Sun Nov 22 15:26:01 CST 2020
     */
    public Float getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticketPrice.ticket_price
     *
     * @param ticketPrice the value for ticketPrice.ticket_price
     *
     * @mbggenerated Sun Nov 22 15:26:01 CST 2020
     */
    public void setTicketPrice(Float ticketPrice) {
        this.ticketPrice = ticketPrice;
    }
}