package com.java.rollercoaster.pojo;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Type.ticket_type
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String ticketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Type.ticket_price
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Float ticketPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Type.ticket_type
     *
     * @return the value of Type.ticket_type
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Type.ticket_type
     *
     * @param ticketType the value for Type.ticket_type
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType == null ? null : ticketType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Type.ticket_price
     *
     * @return the value of Type.ticket_price
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Float getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Type.ticket_price
     *
     * @param ticketPrice the value for Type.ticket_price
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setTicketPrice(Float ticketPrice) {
        this.ticketPrice = ticketPrice;
    }
}