package com.java.rollercoaster.pojo;

import com.java.rollercoaster.service.model.enumeration.TicketType;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Type.ticket_type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    private TicketType TicketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Type.ticket_price
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    private Float ticketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Type.description
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Type.image_url
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Type.ticket_type
     *
     * @return the value of Type.ticket_type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public TicketType getTicketType() {
        return TicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Type.ticket_type
     *
     * @param TicketType the value for Type.ticket_type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public void setTicketType(TicketType TicketType) {
        this.TicketType = TicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Type.ticket_price
     *
     * @return the value of Type.ticket_price
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public Float getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Type.ticket_price
     *
     * @param ticketPrice the value for Type.ticket_price
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public void setTicketPrice(Float ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Type.description
     *
     * @return the value of Type.description
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Type.description
     *
     * @param description the value for Type.description
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Type.image_url
     *
     * @return the value of Type.image_url
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Type.image_url
     *
     * @param imageUrl the value for Type.image_url
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }
}