package com.java.rollercoaster.pojo;

public class userPassword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.phone_number
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.password
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.phone_number
     *
     * @return the value of password.phone_number
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password.phone_number
     *
     * @param phoneNumber the value for password.phone_number
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.password
     *
     * @return the value of password.password
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password.password
     *
     * @param password the value for password.password
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}