package com.java.rollercoaster.pojo;

import com.java.rollercoaster.service.model.enumeration.Role;
import com.java.rollercoaster.service.model.enumeration.UserGender;

public class UserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.user_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.phone_number
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.user_name
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.user_gender
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private UserGender UserGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.user_age
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.role
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private Role Role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.third_party_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String thirdPartyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccount.email
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.user_id
     *
     * @return the value of userAccount.user_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.user_id
     *
     * @param userId the value for userAccount.user_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.phone_number
     *
     * @return the value of userAccount.phone_number
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.phone_number
     *
     * @param phoneNumber the value for userAccount.phone_number
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.user_name
     *
     * @return the value of userAccount.user_name
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.user_name
     *
     * @param userName the value for userAccount.user_name
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.user_gender
     *
     * @return the value of userAccount.user_gender
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public UserGender getUserGender() {
        return UserGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.user_gender
     *
     * @param UserGender the value for userAccount.user_gender
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setUserGender(UserGender UserGender) {
        this.UserGender = UserGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.user_age
     *
     * @return the value of userAccount.user_age
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.user_age
     *
     * @param userAge the value for userAccount.user_age
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.role
     *
     * @return the value of userAccount.role
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public Role getRole() {
        return Role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.role
     *
     * @param Role the value for userAccount.role
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setRole(Role Role) {
        this.Role = Role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.third_party_id
     *
     * @return the value of userAccount.third_party_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.third_party_id
     *
     * @param thirdPartyId the value for userAccount.third_party_id
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccount.email
     *
     * @return the value of userAccount.email
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccount.email
     *
     * @param email the value for userAccount.email
     *
     * @mbggenerated Wed Nov 25 14:54:52 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}