package com.java.rollercoaster.pojo;

public class userPassword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.phone_number
     *
     * @mbggenerated Thu Nov 05 16:41:45 CST 2020
     */
    private Integer phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.password
     *
     * @mbggenerated Thu Nov 05 16:41:45 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.phone_number
     *
     * @return the value of password.phone_number
     *
     * @mbggenerated Thu Nov 05 16:41:45 CST 2020
     */
    public Integer getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password.phone_number
     *
     * @param phoneNumber the value for password.phone_number
     *
     * @mbggenerated Thu Nov 05 16:41:45 CST 2020
     */
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.password
     *
     * @return the value of password.password
     *
     * @mbggenerated Thu Nov 05 16:41:45 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password.password
     *
     * @param password the value for password.password
     *
     * @mbggenerated Thu Nov 05 16:41:45 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}