package com.java.rollercoaster.dao;

import com.java.rollercoaster.pojo.appointment;
import com.java.rollercoaster.pojo.appointmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface appointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int countByExample(appointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int deleteByExample(appointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int deleteByPrimaryKey(String appointmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int insert(appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int insertSelective(appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    List<appointment> selectByExample(appointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    appointment selectByPrimaryKey(String appointmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") appointment record, @Param("example") appointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByExample(@Param("record") appointment record, @Param("example") appointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByPrimaryKeySelective(appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByPrimaryKey(appointment record);
}