package com.java.rollercoaster.dao;

import com.java.rollercoaster.pojo.Balance;
import com.java.rollercoaster.pojo.BalanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int countByExample(BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int deleteByExample(BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int insert(Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int insertSelective(Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    List<Balance> selectByExample(BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    Balance selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") Balance record, @Param("example") BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int updateByExample(@Param("record") Balance record, @Param("example") BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int updateByPrimaryKeySelective(Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated Tue Dec 01 10:59:43 CST 2020
     */
    int updateByPrimaryKey(Balance record);
}