package com.java.rollercoaster.dao;

import com.java.rollercoaster.pojo.facility;
import com.java.rollercoaster.pojo.facilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface facilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int countByExample(facilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int deleteByExample(facilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int deleteByPrimaryKey(String facilityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int insert(facility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int insertSelective(facility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    List<facility> selectByExample(facilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    facility selectByPrimaryKey(String facilityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") facility record, @Param("example") facilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByExample(@Param("record") facility record, @Param("example") facilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByPrimaryKeySelective(facility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table facility
     *
     * @mbggenerated Fri Nov 06 12:17:04 CST 2020
     */
    int updateByPrimaryKey(facility record);
}