package com.java.rollercoaster.dao;

import com.java.rollercoaster.pojo.Type;
import com.java.rollercoaster.pojo.TypeExample;
import com.java.rollercoaster.service.model.enumeration.TicketType;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int countByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int deleteByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int deleteByPrimaryKey(TicketType TicketType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    List<Type> selectByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    Type selectByPrimaryKey(TicketType TicketType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") Type record, @Param("example") TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int updateByExample(@Param("record") Type record, @Param("example") TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Type
     *
     * @mbggenerated Wed Dec 02 01:16:39 CST 2020
     */
    int updateByPrimaryKey(Type record);
}